Repository IdentityPython/JWTConnect-Python-CryptoJWT, pull requests merged in 2020-09, with the labels that each got.

#67 Add optional error holddown for KeyBundle
  src/cryptojwt/key_bundle.py
  tests/test_03_key_bundle.py
Labels: enhancement

#66 Inactive key fixes
  src/cryptojwt/key_bundle.py
  tests/test_03_key_bundle.py
  tests/test_04_key_jar.py
  tox.ini
Labels: bug

#68 Prepare release 1.3.0
  src/cryptojwt/__init__.py
  src/cryptojwt/exception.py
  src/cryptojwt/key_bundle.py
  tests/test_03_key_bundle.py
  tests/test_04_key_jar.py
  tox.ini
Labels: release
